1641618 + 0 in total (QC-passed reads + QC-failed reads)
792764 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
1638620 + 0 mapped (99.82%:-nan%)
848854 + 0 paired in sequencing
424427 + 0 read1
424427 + 0 read2
748282 + 0 properly paired (88.15%:-nan%)
844410 + 0 with itself and mate mapped
1446 + 0 singletons (0.17%:-nan%)
2640 + 0 with mate mapped to a different chr
720 + 0 with mate mapped to a different chr (mapQ>=5)
