#!/bin/bash

cd /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution
tmpDir=$(mkdir -p "/home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/tmp.e5906d0a" && echo "/home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/tmp.e5906d0a")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution

)
(
cd /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution


python $(which encode_qc_report.py) \
	--name 'ENCSR356KRQ (1/400 subsampled)' \
	--desc 'ATAC-seq on primary keratinocytes in day 0.0 of differentiation' \
	--paired-end \
	--pipeline-type atac \
	--peak-caller macs2 \
	--idr-thresh 0.05 \
	--flagstat-qcs /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-270291945/ENCFF341MYG.subsampled.400.trim.merged.flagstat.qc /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-278051304/ENCFF641SFZ.subsampled.400.trim.merged.flagstat.qc \
	--nodup-flagstat-qcs /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/964568587/ENCFF341MYG.subsampled.400.trim.merged.nodup.flagstat.qc /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/956809228/ENCFF641SFZ.subsampled.400.trim.merged.nodup.flagstat.qc \
	--dup-qcs /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-151822900/ENCFF341MYG.subsampled.400.trim.merged.dup.qc /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-159582259/ENCFF641SFZ.subsampled.400.trim.merged.dup.qc \
	--pbc-qcs /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-1191093819/ENCFF341MYG.subsampled.400.trim.merged.dupmark.pbc.qc /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-1198853178/ENCFF641SFZ.subsampled.400.trim.merged.dupmark.pbc.qc \
	--xcor-plots /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/284095168/ENCFF341MYG.subsampled.400.trim.merged.nodup.tn5.no_chrM.R1.25M.cc.plot.png /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/276335809/ENCFF641SFZ.subsampled.400.trim.merged.nodup.tn5.no_chrM.R1.25M.cc.plot.png \
	--xcor-scores /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/1640361180/ENCFF341MYG.subsampled.400.trim.merged.nodup.tn5.no_chrM.R1.25M.cc.qc /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/1632601821/ENCFF641SFZ.subsampled.400.trim.merged.nodup.tn5.no_chrM.R1.25M.cc.qc \
	--idr-plots /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-1256444191/rep1-rep2.idr0.05.unthresholded-peaks.txt.png \
	--idr-plots-pr /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/1633167004/rep1-pr.idr0.05.unthresholded-peaks.txt.png /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/1625407645/rep2-pr.idr0.05.unthresholded-peaks.txt.png \
	--idr-plot-ppr /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/169398562/ppr.idr0.05.unthresholded-peaks.txt.png \
	--frip-macs2-qcs /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/1124314406/ENCFF341MYG.subsampled.400.trim.merged.nodup.tn5.pval0.01.300K.bfilt.frip.qc /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/1116555047/ENCFF641SFZ.subsampled.400.trim.merged.nodup.tn5.pval0.01.300K.bfilt.frip.qc \
	--frip-macs2-qcs-pr1 /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/1969910230/ENCFF341MYG.subsampled.400.trim.merged.nodup.tn5.pr1.pval0.01.300K.bfilt.frip.qc /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/1962150871/ENCFF641SFZ.subsampled.400.trim.merged.nodup.tn5.pr1.pval0.01.300K.bfilt.frip.qc \
	--frip-macs2-qcs-pr2 /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-1694598441/ENCFF341MYG.subsampled.400.trim.merged.nodup.tn5.pr2.pval0.01.300K.bfilt.frip.qc /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-1702357800/ENCFF641SFZ.subsampled.400.trim.merged.nodup.tn5.pr2.pval0.01.300K.bfilt.frip.qc \
	--frip-macs2-qc-pooled /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-795079974/ENCFF341MYG.subsampled.400.trim.merged.nodup.tn5.pooled.pval0.01.300K.bfilt.frip.qc \
	--frip-macs2-qc-ppr1 /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-1523460514/ENCFF341MYG.subsampled.400.trim.merged.nodup.tn5.pr1.pooled.pval0.01.300K.bfilt.frip.qc \
	--frip-macs2-qc-ppr2 /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-1531219873/ENCFF341MYG.subsampled.400.trim.merged.nodup.tn5.pr2.pooled.pval0.01.300K.bfilt.frip.qc \
	--frip-idr-qcs /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-1765245905/rep1-rep2.idr0.05.bfilt.frip.qc \
	--frip-idr-qcs-pr /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/1124365290/rep1-pr.idr0.05.bfilt.frip.qc /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/1116605931/rep2-pr.idr0.05.bfilt.frip.qc \
	--frip-idr-qc-ppr /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-339403152/ppr.idr0.05.bfilt.frip.qc \
	--frip-overlap-qcs /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/1771500479/rep1-rep2.overlap.bfilt.frip.qc \
	--frip-overlap-qcs-pr /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/198185562/rep1-pr.overlap.bfilt.frip.qc /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/190426203/rep2-pr.overlap.bfilt.frip.qc \
	--frip-overlap-qc-ppr /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-1625432576/ppr.overlap.bfilt.frip.qc \
	--idr-reproducibility-qc /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/-230641729/idr.reproducibility.qc \
	--overlap-reproducibility-qc /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/inputs/1121325519/overlap.reproducibility.qc \
	--out-qc-html qc.html \
	--out-qc-json qc.json

diff qc.json /dev/null | wc -l > qc_json_match.txt
)  > '/home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/stdout' 2> '/home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/stderr'
echo $? > /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution
find . -type d -empty -print0 | xargs -0 -I % touch %/.file
)
(
cd /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution
sleep 30
# make the directory which will keep the matching files
mkdir /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/glob-eae855c82d0f7e2185388856e7b2cc7b

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/glob-eae855c82d0f7e2185388856e7b2cc7b/cromwell_glob_control_file

# symlink all the files into the glob directory
( ln -L *qc.html /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/glob-eae855c82d0f7e2185388856e7b2cc7b 2> /dev/null ) || ( ln *qc.html /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/glob-eae855c82d0f7e2185388856e7b2cc7b )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/glob-eae855c82d0f7e2185388856e7b2cc7b | grep -v cromwell_glob_control_file > /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/glob-eae855c82d0f7e2185388856e7b2cc7b.list

# make the directory which will keep the matching files
mkdir /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/glob-3440f922973abb7a616aaf203e0db08b

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/glob-3440f922973abb7a616aaf203e0db08b/cromwell_glob_control_file

# symlink all the files into the glob directory
( ln -L *qc.json /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/glob-3440f922973abb7a616aaf203e0db08b 2> /dev/null ) || ( ln *qc.json /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/glob-3440f922973abb7a616aaf203e0db08b )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/glob-3440f922973abb7a616aaf203e0db08b | grep -v cromwell_glob_control_file > /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/glob-3440f922973abb7a616aaf203e0db08b.list


)
mv /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/rc.tmp /home/xli6/projects/atacseq/atac/cromwell-executions/atac/3653815d-a13c-4737-8183-22aec1b80ee5/call-qc_report/execution/rc
